/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        card: 'var(--card)',
        sub: 'var(--sub)',
        ink: 'var(--ink)',
        muted: 'var(--muted)',
        faint: 'var(--faint)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',
        brand: 'var(--brand)',
        'brand-strong': 'var(--brand-strong)',
        'brand-ink': 'var(--brand-ink)',
        mint: 'var(--mint)',
        sage: 'var(--sage)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        info: 'var(--info)',
        series: {
          1: 'var(--s1)',
          2: 'var(--s2)',
          3: 'var(--s3)',
          4: 'var(--s4)',
          5: 'var(--s5)',
          6: 'var(--s6)',
          7: 'var(--s7)',
          8: 'var(--s8)',
        },
      },
      borderRadius: { card: 'var(--r-card)', ctl: 'var(--r-ctl)', pill: 'var(--r-pill)' },
      boxShadow: { card: 'var(--shadow-card)', pop: 'var(--shadow-pop)' },
      fontFamily: { sans: 'var(--font-sans)', mono: 'var(--font-mono)' },
      fontSize: {
        title: ['21px', { lineHeight: '1.2', letterSpacing: '-0.015em' }],
        h2: ['16px', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        eyebrow: ['11px', { letterSpacing: '0.13em' }],
        label: ['10px', { letterSpacing: '0.13em' }],
        body: ['13px', { lineHeight: '1.5' }],
        value: ['13px', { lineHeight: '1.4' }],
        formula: ['12.5px', { lineHeight: '1.4' }],
        caption: ['11.5px', { lineHeight: '1.4' }],
      },
    },
  },
  plugins: [],
};
